upgrade ember-cli to 2.12.3
ciena-blueplanet/ember-graphlib pull request #57
Opened 2017-07-04 18:12 UTC by helloWorldCindy

**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [ ] #patch# - backwards-compatible bug fix
- [x] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG

Upgrade ember-cli to 2.12.3

2017-07-05 13:30 UTC, notmessenger commented
Change the branch names in:

* https://github.com/ciena-blueplanet/ember-graphlib/blob/master/.travis/maybe-bump-version.sh#L9
* https://github.com/ciena-blueplanet/ember-graphlib/blob/master/.travis/maybe-publish-coverage.sh#L17

2017-07-05 13:31 UTC, notmessenger requested changes

2017-07-05 13:31 UTC, notmessenger commented on .npmignore
> +.eslintrc.js
Locate in file alphabetically

2017-07-05 13:31 UTC, notmessenger commented on .travis.yml
> +  - node_js: 'stable'
Same question as other PRs @juwara0 about whether needed and that I haven't bee doing this and whether should be.

2017-07-05 13:31 UTC, notmessenger commented on package.json
>    "devDependencies": {
`ember-cli-test-loader` should be removed

2017-07-05 13:31 UTC, notmessenger commented on package.json
>      "ember-source": "~2.11.2",
Should be `~2.12.0`

2017-07-05 13:31 UTC, notmessenger commented on tests/.eslintrc.js
> +};
Remove `;`

2017-07-05 13:31 UTC, notmessenger commented on tests/dummy/config/environment.js
>  module.exports = function (environment) {
`ENV.rootURL = '/'` in test configuration should be removed as well

2017-07-05 13:31 UTC, notmessenger commented on tests/dummy/config/environment.js
>  module.exports = function (environment) {
Change `locationType` to `hash` for consistency

2017-07-05 15:01 UTC, helloWorldCindy commented on .npmignore
> +.eslintrc.js
Fixed.

2017-07-05 15:02 UTC, helloWorldCindy commented on package.json
>    "devDependencies": {
Fixed.

2017-07-05 15:02 UTC, helloWorldCindy commented on package.json
>      "ember-source": "~2.11.2",
Fixed.

2017-07-05 15:02 UTC, helloWorldCindy commented on tests/.eslintrc.js
> +};
Fixed.

2017-07-05 15:02 UTC, helloWorldCindy commented on tests/dummy/config/environment.js
>  module.exports = function (environment) {
Fixed.

2017-07-07 15:14 UTC, dafortin commented on .github/PULL_REQUEST_TEMPLATE.md
> +### This project uses [semver](semver.org), please check the scope of this pr:
@juwara0 @notmessenger we should agree on ** or ###. `ember-frost-core` is using ** and `ember-frost-list` is using `###`.

2017-07-07 15:14 UTC, dafortin commented on .travis.yml
>    - EMBER_TRY_SCENARIO=ember-release
We decided to keep `release` `beta` and `canary` for this repo?

2017-07-07 16:48 UTC, juwara0 commented on .travis.yml
>    - EMBER_TRY_SCENARIO=ember-release
Yes, for the shims I have expanded the build matrix.

2017-07-07 17:02 UTC, notmessenger commented on .github/PULL_REQUEST_TEMPLATE.md
> +### This project uses [semver](semver.org), please check the scope of this pr:
Agreed though I'm not concerned with making that determination for the sake of this PR.  Consistency between the repos will be addressed in a separate effort.

(if there was an obvious pattern and this deviated, yes - it should be fixed now.  but to use sidetrack this PR to determine a desired pattern is not anything we need to do right now)

2017-07-07 17:02 UTC, juwara0 commented on .github/PULL_REQUEST_TEMPLATE.md
> +### This project uses [semver](semver.org), please check the scope of this pr:
Just a quick look through the repos and I am see more `**`. We can address a consistent approach across the repos in a separate effort.

2017-07-07 17:04 UTC, notmessenger commented on .npmignore
> +.eslintrc.js
Still isn't alphabetical :-)

2017-07-07 17:07 UTC, juwara0 commented on .npmignore
> +.eslintrc.js
Fixed

2017-07-07 17:07 UTC, notmessenger approved these changes

2017-07-07 17:07 UTC, notmessenger commented
👍

2017-07-07 17:27 UTC, dafortin commented on .github/PULL_REQUEST_TEMPLATE.md
> +### This project uses [semver](semver.org), please check the scope of this pr:
I'm good with this. As long as we are aware that we need to fix that later. (it's a very minor thing)

2017-07-07 17:29 UTC, merged